plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-script-daemon.cjs
    spec: "@yarnpkg/plugin-script-daemon"

yarnPath: .yarn/releases/yarn-3.8.7.cjs
